version: '3.3'
services:
  db:
    image: mysql:5.7
    #restart: always
    environment:
      MYSQL_DATABASE: debezium
      MYSQL_USER: user
      MYSQL_PASSWORD: debezium
      MYSQL_ROOT_PASSWORD: debezium
    ports:
      - 3306:3306
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: